#!/usr/bin/env node
/* =============================================================
   build.js — enrich seed.js with TMDB data and write data.js
   -------------------------------------------------------------
   Usage:
     TMDB_API_KEY=your_key node build.js
     TMDB_API_KEY=your_key WATCH_REGION=EG node build.js   (default region: EG)

   What it adds to each title:
     poster    small poster image URL
     overview  TMDB description
     imdb      full IMDb URL
     rating    TMDB score (0–10, one decimal)
     runtime   minutes (movies / episode length)
     genres    up to 3 genre names
     watch     where-to-watch in your region: { link, flatrate[], rent[], buy[] }

   Notes:
   - Get a free key at https://www.themoviedb.org/settings/api (v3 auth).
   - Requires Node 18+ (uses built-in fetch).
   - Results are cached in .tmdb-cache.json so re-runs are fast. Delete that
     file to force a full refresh.
   - Editorial fields (universe/saga/phase/notes) always come from seed.js and
     override anything from TMDB.
   ============================================================= */

const fs = require('fs');
const path = require('path');

const KEY = process.env.TMDB_API_KEY;
if (!KEY) { console.error('Missing TMDB_API_KEY. Get one free at themoviedb.org → Settings → API.'); process.exit(1); }
const REGION = (process.env.WATCH_REGION || 'EG').toUpperCase();
const IMG = 'https://image.tmdb.org/t/p/w185';
const CACHE_VER = 3;

const seed = require('./seed.js');
const CACHE_FILE = path.join(__dirname, '.tmdb-cache.json');
let cache = {};
try { cache = JSON.parse(fs.readFileSync(CACHE_FILE, 'utf8')); } catch (e) {}

const sleep = ms => new Promise(r => setTimeout(r, ms));

async function api(endpoint, params = {}) {
  const url = new URL('https://api.themoviedb.org/3' + endpoint);
  url.searchParams.set('api_key', KEY);
  for (const k in params) if (params[k] != null) url.searchParams.set(k, params[k]);
  for (let attempt = 0; attempt < 4; attempt++) {
    const res = await fetch(url);
    if (res.status === 429) { await sleep(1500); continue; }          // rate limited: back off
    if (!res.ok) throw new Error(endpoint + ' → HTTP ' + res.status);
    return res.json();
  }
  throw new Error(endpoint + ' → repeated 429s');
}

// strip "— Season N" and trailing "*" for cleaner searches
function searchTitle(t) { return t.title.replace(/\s*—\s*Season.*$/i, '').replace(/\*+$/, '').trim(); }

async function resolveId(t) {
  if (t.tmdb_id && t.tmdb_type) return { id: t.tmdb_id, mt: t.tmdb_type };
  const primary = (t.type === 'series') ? 'tv' : 'movie';
  const secondary = primary === 'movie' ? 'tv' : 'movie';
  const q = searchTitle(t);
  for (const mt of [primary, secondary]) {
    const params = mt === 'movie' ? { query: q, year: t.year } : { query: q, first_air_date_year: t.year };
    const res = await api('/search/' + mt, params);
    const hit = (res.results || [])[0];
    if (hit) return { id: hit.id, mt };
  }
  return null;
}

async function enrich(t) {
  if (cache[t.id] && cache[t.id]._v === CACHE_VER) return { ...t, ...cache[t.id].data };
  let data = {};
  const r = await resolveId(t);
  if (r) {
    const d = await api('/' + r.mt + '/' + r.id, { append_to_response: 'external_ids,watch/providers' });
    const prov = (((d['watch/providers'] || {}).results) || {})[REGION] || null;
    const names = a => (a || []).map(p => p.provider_name);
    data = {
      tmdb_id: r.id, tmdb_type: r.mt,
      poster: d.poster_path ? IMG + d.poster_path : null,
      overview: d.overview || null,
      imdb: (d.external_ids && d.external_ids.imdb_id) ? 'https://www.imdb.com/title/' + d.external_ids.imdb_id + '/' : null,
      rating: d.vote_average ? Math.round(d.vote_average * 10) / 10 : null,
      runtime: d.runtime || (d.episode_run_time && d.episode_run_time[0]) || null,
      genres: (d.genres || []).map(g => g.name).slice(0, 3),
      watch: prov ? { link: prov.link || null, flatrate: names(prov.flatrate), rent: names(prov.rent), buy: names(prov.buy) } : null
    };
  }
  cache[t.id] = { _v: CACHE_VER, data };
  return { ...t, ...data };
}

(async () => {
  const out = [];
  let done = 0, missed = [];
  for (const t of seed.titles) {
    try {
      const e = await enrich(t);
      if (!e.tmdb_id) missed.push(t.title);
      out.push(e);
    } catch (err) {
      console.error('\n! ' + t.id + ': ' + err.message);
      out.push(t); missed.push(t.title);
    }
    done++;
    process.stdout.write(done % 10 === 0 ? '' + done : '.');
    if (done % 5 === 0) await sleep(250);              // gentle pacing
  }
  fs.writeFileSync(CACHE_FILE, JSON.stringify(cache));

  const cfg = { ...seed.config, updated: new Date().toISOString().slice(0, 7), watchRegion: REGION };
  const banner = '/* AUTO-GENERATED by build.js — do not edit by hand. Edit seed.js and re-run. */\n';
  const js = banner +
    'window.MCU_CONFIG = ' + JSON.stringify(cfg, null, 2) + ';\n\n' +
    'window.MCU_DATA = ' + JSON.stringify(out, null, 2) + ';\n';
  fs.writeFileSync(path.join(__dirname, 'data.js'), js);

  console.log('\n\nWrote data.js — ' + out.length + ' titles, region ' + REGION + '.');
  if (missed.length) console.log('No TMDB match for ' + missed.length + ' (pin tmdb_id in seed.js): ' + missed.join(', '));
})();
